pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'nhsdigital'
    scannerMode: 'CLI'
    configMode: 'file'
    extraProperties: |
      sonar.javascript.lcov.reportPaths=coverage/lcov.info
      sonar.language=js
      sonar.projectKey=nhsuk-prototype-kit
      sonar.sourceEncoding=UTF-8

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: true
    
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    customCommand: run build
    verbose: true

- task: Npm@1
  displayName: 'npm run test'
  inputs:
    command: 'custom'
    customCommand: run test
    verbose: true

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
  displayName: 'Run SonarCloud Code Analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'

- task: sonarcloud-buildbreaker@2
  displayName: "Break the build if the quality gate fails"
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'nhsdigital'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'

    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
